kind = "api"
previewPath = "/"
title = "SafeRouteX AI"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "SafeRouteX AI"
paths = ["/"]

[services.development]
run = "python python-app/app.py"

[services.production]

[services.production.build]
args = ["echo", "no-build"]

[services.production.build.env]
NODE_ENV = "production"

[services.production.run]
args = ["python", "python-app/app.py"]

[services.production.run.env]
PORT = "8000"
NODE_ENV = "production"

[services.production.health.startup]
path = "/"
