kind = "api"
previewPath = "/"
title = "SafeRouteX AI"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "SafeRouteX AI"
paths = ["/"]

[services.env]
PORT = "8000"

[services.development]
run = "bash start.sh"

[services.production]
run = "bash start.sh"
build = "pip install -r python-app/requirements.txt"

[services.production.health.startup]
path = "/"
