kind = "api"
previewPath = "/"
title = "SafeRouteX AI"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "SafeRouteX AI"
paths = ["/"]

[services.development]
run = "python /home/runner/workspace/python-app/app.py"

[services.production]

[services.production.build]
args = ["pip", "install", "-r", "python-app/requirements.txt"]

[services.production.run]
args = ["bash", "start.sh"]

[services.production.run.env]
PORT = "8000"

[services.production.health.startup]
path = "/"
